version: 2.1

commands:
  print_pipeline_id:
    description: "my first command"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

workflows:
  version: 2
  build:
    jobs:
      # - build
      - test-commands
#       - save_hello_world_output
#       - print_output_file:
#           requires:
#             - save_hello_world_output

jobs:
  test-commands:
    docker:
      - image: circleci/node:13.8.0
    steps:
     - print_pipeline_id        
  save_hello_world_output:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: echo "hello world" >> ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
